#!/user/bin/env perl

use 5.010;
use Getopt::Std;
use Data::Dumper;
our $opts={};

#open my $confh,"< ./hosts" or die "can not open hosts $!";
#close $confh;

getopts('ab',$opts);
&before_reboot() if   $opts->{'a'} == 1  ;
&after_reboot()  if   $opts->{'b'} == 1  ;

sub analyze_hosts{
}

sub before_reboot{

}

sub after_reboot{

}
