#!/bin/bash
Usage(){
#before 
 echo "Usage:
     $0   time
 egg: $0  \"2013-09-18 14:15:00\"
" 
    exit 1
}
checkfinish(){

    echo 

}
if [[ $# != 1 ]]
then
    Usage
fi 

curtime=$1
# change time in the front 
echo change time
date -s  "$curtime"
if [[ $? != 0 ]]
then
    echo "$curtime is not correct Time Format"
    Usage
fi
hwclock -w
echo change time finish 
unset curtime

mkdir log
# cloudview media rename
mv cloudview*  cloudview
if [[ $? != 0 ]]
then
    echo "Make sure cloudview software  is in ( cloudview_deploy ) directory !"
    exit 1
fi

########################################
#   handle hosts file 
######################################
if [[ -f  ip_map    ]]
then 
   sed -i 's/  / /g' ip_map 
   echo "127.0.0.1 localhost" > hosts  
   awk  '{printf("%s   %s\n", $1,$2)}' ip_map >> hosts
else
    echo please check ip_map  is exist
    exit 1
fi
cp -rf /etc/hosts  /etc/hosts.bak
cp -rf hosts  /etc/  
########################################
#  extract  Support
###################################
tmppath=`pwd`
cd cloudview/Supports 
for i  in `ls *.gz`
do
    gzip -d $i
done
for i  in `ls *.tar`
do
    tar -xvf  $i
done

cd $tmppath

########################################
# no_passwd 
########################################
nodenum=`grep hvn ./hosts | wc -l  | awk '{print $1}'` # 
tmppath=`pwd`
nodelist=`awk '{print $1 }' ip_map | perl -lane  ' push @a,$_ ;END{print join ",",@a }'`
tmppasswd='111111'
cd ./utility/nopasswd/
chmod a+x * 
./xmakessh  --pass  $tmppasswd  --nodes  $nodelist 
cd $tmppath
unset tmppath
unset nodenum
unset tmppasswd
unset tmppasswd

#########################################
#  config  before reboot 
######################################
ip=''
name=''
manage_eth="eth1"
business_ip=''
business_eth="eth0"
business_br="br0"
business_netmask='24'


for  line  in `egrep  -v '^\s*#' ip_map | grep hvn | sed  -e 's/  / /g'  -e 's/ /:/g'`
do
    ip=`echo $line | awk -F: '{print $1}'`
    name=`echo $line | awk -F: '{print $2}'`
    business_ip=`echo $line | awk -F: '{print $3}'`
    echo "########################################"
    echo "# $ip  $name  $business_ip"
	if [[ "X$name" == "Xhvn1" ]];then
        # bridging bussiness  ip
	    cd utility/
	    touch ../log/bridging.log
        nohup sh   bridging.sh $business_ip $business_eth $business_br  $business_netmask > ../log/bridging.log    2>&1 &  
        cd ..
        	
        #excute A1  master 
        cd master
	    touch ../log/master_before.log
	    nohup sh master_hyper_before_reboot.sh  $manage_eth $ip  > ../log/master_before.log   2>&1  &
	    cd ..
        echo "########################################"
		continue
	fi            

	#copy file	
    cd ..  
    scp  -r   cloudview_deploy/     ${ip}:/root/  
    cd cloudview_deploy
    # bridging bussiness ip
    tmp_cmd="cd /root/cloudview_deploy/utility/;touch ../log/bridging; nohup sh   bridging.sh $business_ip $business_eth $business_br  $business_netmask   >../log/bridging.log    2>&1 & " 
    ssh $ip $tmp_cmd 
    unset tmp_cmd 
    
  	#excute B1  hvn
    tmp_cmd="cd /root/cloudview_deploy/hvn ;touch ../log/${name}_before.log ;nohup  sh  hvn_before_reboot.sh  $manage_eth  $ip  > ../log/${name}_before.log  2>&1 & "

    ssh $ip  $tmp_cmd 
	unset tmp_cmd
#	echo $ip
     echo "########################################"
done 
unset ip
unset name 
unset business_ip
unset manage_eth
echo 'Wait 30 Second!'



for  line  in `cat hosts| grep hvn  | grep -v hvn1 `
do
    ip=`echo $line | awk -F: '{print $1}'`
    name=`echo $line | awk -F: '{print $2}'`
    business_ip=`echo $line | awk -F: '{print $3}'`
    

done
checkfinish 

